### ISSUE TITLE
v1.2.0 Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#11]
Minor update for **mini.css**.
## Changes
- [ ] New components: Checkboxes, Radio Buttons, Toggle Switches
- [ ] Documentation for said components
- [ ] Javascript support library project launch
- [ ] Aria support in demo pages
- [ ] Make tables responsive

**Comment by Chalarangelo** [comment]
Changes have been postponed until **v2.0.0** in order for them to be applied to the redesigned framework. Bear in mind that some minor changes like table responsiveness might be applied in earlier patches.
