### ISSUE TITLE
v2.0.0 (Fermion) Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#12]
Major framework update. This update will probably launch sometime in 2017 (probably sometime Q1).
### Module Restructure
-  ~~Merge **Base** and **Grid** into **Base**~~.
-  ~~Merge **Button** and **Checkbox** (name pending) into **InputControl**~~.
-  ~~Move form and table styling to base, make default, add remaining styles in there and remove the two modules entirely. (No need to use defaults if there is already a style defined and you can always turn those off)~~.
- ~~Merge **Nav**, **Dropdown** and **Tab** into one module **Navigation**~~.
-  ~~Merge **Progress** and **Spinner** into **Progress**~~.
- ~~Restructure both **Utility** modules to push some styles into other modules and merge the rest into one~~.
- ~~Merge **Modal** and most of the Utility containers, as well as **Label** into **Container**~~.
- ~~Merge **Carousel** and **Collapse** into **Presentation**~~.
- [x] Complete the module restructure as specified in issue #14.
## Responsiveness
- [x] Responsive `pre` elements.
- [x] Responsive tables.
- ~~Responsive media.~~ Will be added later.
## Component and style changes
- [x] Add fancy styling for `hr`.
- [x] `uncertain` Add fancy sidebar (30px wide with code icon (`</>`) using `:before`) for `pre` code blocks.
- [x] Make contextual text work based on `mark` element.
- [x] Change styling to a material-like design.
- ~~Rebuild dropdowns from scratch.~~ - Removed dropdowns entirely.
- [x] Rebase **grid** on `flex`.
## New Modules
- [x] Create component styles for checkboxes, radio buttons and switches
### Other Changes
- [x] Bump to **Normalize v5.0.0**.
- ~~Rebase modal dialog's styling using panel styling.~~ - Removed modal dialogs entirely.
- [x] Drop older browser support (specifically IE8 and older).
- [x] Change navigation to be based on the `nav` element.
- [x] Accessibility support in demos.
- ~~Javascript support library.~~ - Might be added later down the line, not required for release.
- [x] ~~Documentation pages by version.~~ Issue #33 
- [x] Browser support graph in the style of caniuse.
- [x] Update **README**, update demo pages to use the v2 stylesheet instead of the commit one.

**Comment by Chalarangelo** [comment]
Released **Fermion**!
