### ISSUE TITLE
Fermion base rebuild

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#13]
## Tasks:
- [x] Bump to latest Normalize. (current **v5.0.0)
- [x] Styling for headers, paragraphs.
- [x] Styling for code elements.
- [x] Styling for horizontal rules.
- [x] Styling for small scripts.
- [x] Styling for mark elements and contextuals.
- [x] Styling for hyperlinks.
- [x] Styling for bold and auxiliary elements and fixes.
- [x] Form element styling.
- [x] Table styling.
- [x] Responsiveness for images.
- ~~Media responsivenes~~.
- [x] Reponsiveness for tables.
- [x] Grid based on _flexbox_.
- [x] Navigation (based on `nav`), `header`, `footer`.
- [x] Link style for buttons. ~~Special button style for certain small links.~~ 
- [x] Custom checkboxes, radios, file uploads etc.

**Comment by Chalarangelo** [comment]
Core implementation has been mostly completed, minor additions are still being made, but the core will be complete very very soon.
