### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#2]
Some things that need to be done at any possible time:
- [ ] A **material-design** module and/or flavor
- [ ] Alternate grid system utilising `flexbox` or `grid` (or both as separate replacement modules)
- [ ] Flavor pages as style guides
- [x] Package for NPM and Bower (if possible)
- [ ] Bootstrap flavor and migration guide

**Comment by Chalarangelo** [comment]
Moved needed changes to milestones, issue will close.
