### ISSUE TITLE
v2.0.1 (Fermion) Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#49]
As mentioned in #47, #48, there is a need to move `@import` declarations out of the `_core.scss` file. This is an important patch that needs to be applied as soon as possible.

## Changes

- [x] Move `@import` declarations out of `_core.scss` and into the flavor files.
- [x] Move mixin calls inside the flavor files, so that mixins are right below their `@import`.
- [x] Update documentation pages to reflect that the `_core.scss` file does not inclue the `@import` declarations and that they have been moved to the flavor files instead (`customization.html` & `index.html`).
