### ISSUE TITLE
v2.0.2 (Fermion) Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#55]
- [x] Resolve #52 by providing new color hues for `.secondary` and `.tertiary`.
- [x] Update all demo pages to use the new colors reflecting the changes.
- [x] Create new flavor, provide a simple demo Codepen to view. - #56 
- [x] Update doc pages to use the `v2.0.2` `mini-default` flavor in order for the new color scheme to be shown.
- [x] Document new flavor in the `flavors` page. Update `mini-default` description to mirror latest version, as well as to say that it has been fine-tuned to be colorblindness-friendly.
