### ISSUE TITLE
v2.1.0 (Fermion) Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#57]
- [x] #40: Update buttons to use the ARIA `role="button"`.
- [x] #41, #40: A pure CSS tootip can be created and could fit in the **contextual** module. However, if the size is rather large and bloats the module, a separate repository should be created to ship it with certain flavors. Try to utilize the `aria-label=""` attribute for its content.
- [x] #41: Possibly retest the `tooltip` and figure out if some of the calculations are wrong for larger tooltips (they seem to be).
- [x] #42: An extension class for the `<footer>` element should be implemented to address the issue.
- [x] Look into #50, #51 and #21 in order to update the **input_control** module. Some or all of these issues might not be addressed in this update.
- [x] Look into #26 and maybe implement an extension class for the `<header>` element to address the issue.
- [x] #53: Add a flag to enable the functionality described in the issue and create certain classes that will only be available if the flag is set to `true` in order to add this functionality to the grid system.
- [x] Add a flag allowing flavors to enable or disable horizontal tables.
- [x] Retest the `breadcrumbs` component code and update it if any problems are found with the borders etc.
- [x] Update the `<nav>` component to include styling an optional sidebar for subcategories.
- [x] Add support for ARIA-based buttons to `header` element in `navigation` module. Test if the very specific rules such as `a.button` and `label.button` are necessary to overwrite the default styling (they probably are) and, if not so, get rid of them.
- [x] Add support for ARIA-based buttons to `.card.section`.
- [x] Probably remove the endless list of selectors used for `[disabled]`, `:focus`, all the `:invalid` variants and `[readonly]` `input` elements inside the list `input_control` module and just use a generic `input, textarea, select` selector to deal with everything. Most of the unstyled elements will be affected just a little bit.
- [x] Use `@supports` to determine if `calc()` can be used for `tooltip`, otherwise keep default value specified (`left: 50%`).
- [x] Figure out how many of the `:not(.bottom)` selectors are needed for `.tooltip`, replace wherever possible.
- [x] Test if `progress.nano`'s `calc()` directives behave properly, maybe tweak `calc()` to only work with values different from `0`.
- [x] #22: ~~Add a *media object* block element in `utility` module to deal with the most common media object situation that people seem to be facing.~~ Document the *media object* pattern with proper examples, using `grid` module.
- [x] Update documentation pages to use the `v2.1.0` version of the toolkit's `mini-default` flavor.
- [x] Recalculate size of toolkit, update pages accordingly.
- [x] Rebrand as framework instead of toolkit, framework seems to be a better umbrella term than toolkit. Technicalities aside, I prefer the term framework.
- [x] Add easy-to-use menu system in all module pages (something like a second header to allow for easier navigation among modules).
- Update documentation for said changes, especially the `customization.html`  and `quick_reference.html` pages, along with the module pages of the changed modules.
  - [x] Update `grid.html` to include explanation of predefined layouts.
  - [x] Update `navigation.html` to include explanation of `.sticky` rules.
  - [x] Document `[role="button"]` updates in `navigation.html`'s `header` element.
  - [x] Document the addition of `[role="button"]` in `input_control.html`.
  - [x] Explain `.fluid` `.input-group`s in `input_control.html`.
  - [x] Update `contextual.html` for `tooltip` component.
- [x] #40: Add more ARIA-related examples in documentation.
- [x] #54: Add examples and notes to showcase the limitations and shortcomings of the `table` module's headers and structure.
- [x] Add the required sections to `quick_reference.html`, update with Codepens etc.
- ~~Create new flavor, `mini-classic`, address #45 by using Bootstrap-like naming.~~
- ~~Document `mini-classic` flavor in `flavors.html`, add codepen demo.~~
- [x] Update `mini-sucroa` with tooltips etc.
- [x] Update all links and embedding instructions to mirror the latest `v2.1.0` version of the toolkit.
- [x] Update README, CHANGELOG etc.

**Comment by Chalarangelo** [comment]
**Estimated release date**: Late February, 2017.

**Comment by Chalarangelo** [comment]
### Update

Lots of minor changes, additions and features have just been added to the list. Hopefully, I will be able to add all of these before the end of February, but the release might get pushed back a couple of days.

**Comment by Chalarangelo** [comment]
### Update

Most of the work on **v2.1.0** has been completed. Flavor updates are the only thing remaining to be implemented until release.

**Estimated release date:** 21st February 2017

**Comment by Chalarangelo** [comment]
### Update

The promised *mini-classic* flavor will not ship with **v2.1.0** or in fact any other release. This decision was made due to three key reasons:

1. The *mini-classic* flavor would just be a worse version of the *mini-default* flavor, the only difference being some minor design decisions and naming conventions.
2. The *mini-classic* flavor would look far too much like a Bootstrap template or the way Bulma looks, which is pointless, due to the fact **mini.css** is not trying to imitate those frameworks, but rather provide a decent alternative to them. Therefore, copying their style would not be appropriate.
3. Finally, the lack of manpower on the **mini.css** team (I work on it alone) limits the possibility that many flavors will be supported officially and maintained properly, thus I will try to stick to the *mini-default* and *mini-sucroa* flavors, which are both properly maintained. If I somehow find a way to maintain more flavors, I will reconsider the possibility of implementing *mini-classic*, however I will most likely pursue the addition of new, more stylish and varied flavors instead.

Apart from that, most of the other things in the roadmap have been implemented, so **v2.1.0** should be released very soon!
