### ISSUE TITLE
v1.1.0 Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#6]
Minor update to **mini.css**.
## New features
- [x] Spinner support (font independent, 2 variants)
- [x] Bootstrap flavor
- [x] Support for `:disabled` class in disabled styles (issue #8)
- ~~Bootstrap migration guide~~
- ~~Lite version of current flavors (removing some modules and styles probably)~~
- [x] Support for `:hover` styling in thumbnails (issue #10)
## Bug fixes
- [x] Disabled buttons not behaving properly (issue #7)
- [x] Support for close utility `:active` and `:focus` (issue #9 )
## Other changes
- [x] Code cleanup and optimization (might remove some excessive styling in some modules)
- [x] Spinner documentation in both modules pages, menu links, front page links
- ~~Changes to the way menus and dropdowns show in flavor pages and module demos~~

**Comment by Chalarangelo** [comment]
203100b : Resolved some bugs and added a minor feature.

**Comment by Chalarangelo** [comment]
0139657 : Added spinner module.

**Comment by Chalarangelo** [comment]
8c2c7d6: Resolved thumbnail issue.

**Comment by Chalarangelo** [comment]
478d32e: Code cleanup and optimizations.

**Comment by Chalarangelo** [comment]
Some changes postponed until version **v2.0.0**.
