### ISSUE TITLE
v2.1.1 (Fermion) Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#62]
## Overview

The next release of **Fermion** will mostly deal with codebase cleanup and minor changes to the way the framework works. It's a pretty behind-the-scenes patch that should pave the way for the next few patches, that will slowly but steadily introduce new features and minor changes to the framework's inner workings.

## Estimated release

**v2.1.1** has no release date set in stone yet, but it will be out mid-to-late April, depending on how development goes. *There is a very slight chance that the release date will be early April.*

## List of upcoming changes

**Codebase cleanup and restructure**: 

- [x] Certain changes will be made to the `.scss` files to make their stucture more usable and less confusing to newcomers. 
- [x] More default values will be introduced wherever possible to make the framework less dependent on user-specified values and less prone to mistakes.
- [x] `@media` queries will be updated to explicitly work on screens and not printers, so that the print styles that are coming later down the line can be implemented more easily.
- [x] More flags might be introduced to modules, so that it is easier to tweak what features are on or off. Some flags will be *hidden* so that inexperienced users do not accidentally break their flavors.
- [x] Mixins might get their own files, so that they are easier to call, extend and include.

**Documentation changes:**

- [x] Add documentation for new flavor, responsive hiding.
- [x] Parts of the documentation will be clarified and either the wiki will be rebooted (#38) or new pages will be introduced to the documentation of the site, so that developers can get a more advanced understanding of how to tweak the framework.
- [x] **Templates** for common designs will be introduced both via Codepen links and demo pages, as well as downloadable starter sites.
- [x] Change preferred CDN from `rawgit` to `gitcdn` (#64).

**New features:**

- [x] Possible new flavor (`barebones` is the current codename I am using) that will be smaller, easier to use and cut out all the fat of certain features that are not widely used in websites.
- [x] Possible addition of `figure` and `figcaption` styles - might be pushed back to next release.
- [x] Possible introduction of screen-specific `.hidden` classes (both accessible and normal) to deal with a common enough problem (#61).

**Bug fixes:**

- [x] Deal with the problematic rendering of `.button-group` under smaller screens (vertical grouping) on Chrome (#63).

**Comment by Chalarangelo** [comment]
## Update

The promised `barebones` flavor is mostly complete (minor changes might be required before release). Its official name is **lite** (`mini-lite`) and, as of the latest commit, is under 5KB. This flavor will serve as a minimum style guide for websites that need just a very lightweight set of fixes and basic CSS rules.

**Comment by Chalarangelo** [comment]
## Update

The wiki will not be rebooted, but new documentation pages will be added as documentation for the code and how to contribute/maintain it etc.

**Comment by Chalarangelo** [comment]
## Update

Customization documentation is about halfway through, some bugs have been squashed (namely #63 was just fixed) and a few more things are in the works. Release date not set yet, but probably within schedule (late April).

**Comment by Chalarangelo** [comment]
## Update

A lot of the work is already done, most of the customization documentation will be completed until tomorrow and most of the other changes are either already completed or underway. I am aiming for an **April, 21st** release day, but this is not yet final and might get pushed back up to a week (based on internal testing and feedback).

**Comment by Chalarangelo** [comment]
## Update

**Templates** are the only thing not yet added to **v2.1.1**, meaning that the release is a couple of days away at most, if not mere hours. Stay tuned!

**Comment by Chalarangelo** [comment]
## Update

Everything is looking good so far, the update will be live later today.

**Comment by Chalarangelo** [comment]
## Release

Ready to roll!
