### ISSUE TITLE
v2.1.3 (Fermion) Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#70]
## Overview

**v2.1.3** is going to bring a design overhaul, making the framework prettier (hopefully), along with certain changes to the presentation of documentation, to make it easier for new users to access the information they need. Apart from that, a dark flavor is in the works, which will most likely release in this patch.

## Estimated release

**v2.1.3** development is starting today (27/04/2017), hopefully the release is no more than three weeks away. More information will be available as everything progresses. 

## List of upcoming changes

- [x] Design overhaul for the `default` flavor. Lots of feedback has lead to the decision to redesign **mini.css** and make it more sleek and better-looking.
- [x] Documentation updates and possibly a new *elements* view for browsing the docs.
- [x] Dark flavor (`mini-dark`) is in the works already, as many of you have requested.

## Notes

- `print` styles are already in the works, but they will be postponed until the next release most likely.
- Some open issuses, such as #19 and #20 are currently being looked into. Especially #19 along with a few other things might make it into this release or the next as *bleeding-edge* features, meaning they will not be in the `default` flavor, but hopefully they will be into a flavor for people wanting the latest and greatest CSS has to offer.

**Comment by Chalarangelo** [comment]
## Update

`mini-default` has been updated and tested internally. The look of the flavor is significantly improved, whereas the size has been reduced by about `0.08KB` (gzipped). The `mini-dark` flavor will be based on this updated version.

`mini-dark` has also been tested internally and is ready to release in this update. Some tweaks might be required in the future, but the color palette seems to work well enough right now.

**Comment by Chalarangelo** [comment]
## Update

Some minor changes were made to the codebase, effectively shrinking the framework's size a little bit, plus breaking support for some legacy browsers (~0.5-1% of internet users). The docs are being updated with a sidebar to help navigating modules and components on most devices and the modules overview page will be revamped to include lists of components in each module, allowing for easier finding of elements. The customization docs will also receive a similar update to help developers. Finally, if everything goes smoothly, the landing page will see a bit of an update to look a bit more modern and less clumsy, but no promises yet.

*Date not yet set, but shouldn't be too long.*

**Comment by Chalarangelo** [comment]
## Update

Lots of changes in the docs across the board, things are looking good so far. If everything goes my way, I might actually manage a very very early release (today). No promises, yet!

**Comment by Chalarangelo** [comment]
Ready to release already! :tada:
