### ISSUE TITLE
v2.3.0 Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#76]
## Overview

~~**v2.2.1**~~**v2.3.0** is going to contain a host of new features and additions, as well as bug fixes and updates, dealing with problems in all modules and polishing up most of the components provided. Due to the fact that **v2.2.1** was delayed a lot, I decided to drop the minor patch update and merge it with **v2.3.0**, so that more things can be added and fixed in one single release.

## New features & components

- [x] A `modal` component will be added, as requested in the past (see the discussion in #46).
- [x] An Android-style `switch` component will be added. Mainly targeted at PWAs and mobile-centric flavors.
- [x] `.scrollable` tables, allowing a better view for data. Bear in mind this might be pushed back to the next update, as it is certainly unstable so far.
- ~~Some atomic CSS classes might be added to help make layouts and other things easier for beginners.~~ (See comments)

## Bug fixes/updates/polishing up

- [x] Reworked color palette, especially the gray tones, making buttons and code markup easier on the eyes.
- [x] Slight update to the `progress` module's bars to make them look more modern (rounded edges and a bit less thickness are what I'm thinking of).
- [x] Updates to the `input_control` module, especially `.input-group` components for convenience. This might actually happen either under the hood or not at all, based on internal tests and use-cases. *Please report any trouble you had with the module and/or layout ideas that you had trouble implementing with the specific components.*

## Documentation

N/A yet.

## Miscellaneous

- [x] Updates to the `package.json` file, removing the `doc` folder to minimize download size, as well as updating the structure etc.
- [x] `.npmignore` should now ignore the `docs` folder.
- [x] Any and all work for updates will move to the `next` branch from now on.
- [x] Add a `$_1px` variable to calculate the `rem` value of `1px` whenever possible.
- It is possible that variable mapping might make it into this update, but 99% it will be pushed back to the next one, as it will require a lot of creative thinking and changes to existing code.

## Release date

There is no solid estimate yet, but this update will be releasing sometime this month. I will take as much time as required to make this update stable and content-rich, so that later updates build upon it and start addressing #19, which is becoming a reasonably pressing matter.

**Comment by semtle** [comment]
I'm you fan.

**Comment by Chalarangelo** [comment]
## Update

Due to me working more on the React library for the framework, the next release will be later this month, but it is going to be a substantial one, adding the last few much needed components (such as modals and switches). There might also be a couple of hotfixes coming this week or the next one to make everything smoother. From there on out, it's going to be patches and bug fixes until everything is stable and #19 has been resolved fully to move to **v3.0.0**. Thank you all for the support and patience! 😉

**Comment by Chalarangelo** [comment]
## Update

Rebranded as **v2.3.0**. The update is substantial enough to be a minor update instead of a patch, plus the fact that the bug fixes are very vaguely described so far and there is a lot of uncertainty as to what bug fixes will actually be included in this version.

## Notes & progress

1. The fixes and updates to `input_control` were originally planned to be an extensive overhaul of the way `.input-group` groupping works, however there are ways to deal with this in a better fashion, without breaking existing layouts. That is, adding a `.vertical` class (part of the atomic CSS additions), which will most likely make it easier to align forms in a vertical manner, which is exactly the kind of thing that the modern web needs. By keeping the previous layout system, things like checkboxes and other things will not break, allowing for a better overall experience and more options for developers. *Feedback appreciated.*
2. The color palette has been (partially) reworked, some more changes might be made, but the desired effect has been achieved for the screen types and configurations that were to be targeted.
3. A lot of selector updates are happening under the hood, especially in complex selectors like the ones present in `tab` and `input_control`, so that more will be done with less effort and space taken. Parsing should be faster across the board, while everything should run just about the same.
4. The `.modal` component is already completed and documentation has been added to reflect that. It's really lightweight and works fine on all systems. I will also add notes for using `role="dialog"` to add accessibility before release (done).
5. The `.switch` component is now complete, along with many minor additions and changes to checkboxes & radio buttons, one of which is support for `rem`-based sizing.
6. The new `$_1px` variable is calculated from the `font-size` of `html` and can be used to replace the value of `1px` anywhere with its `rem` counterpart. The necessary changes have been made in all the flavors that were `rem`-based, fully transitioning to a `px`-independent system.
7. The `.scrollable` tables are already added and they work fantastic (very similarly to the `.horizontal` ones). I'm really excited about this (I have an idea on how to use them to improve the way we display data on the web, maybe a project for later). 
8. More stuff is coming in this update, some atomic css will be added almost certainly to make the `grid` module a bit more flexible (will also help `header` content alignment). I'll start working on these now to see what I can add without bloating the framework. Size as of now is at **6.67KB gzipped**, which is not that big considering how many things were added in already. Stay tuned for more updates!

**Comment by Chalarangelo** [comment]
## Update

As far as **atomic** css classes are concerned, I took a long, hard look and I realized that, without a basic understanding of CSS, they wouldn't do anyone any good. That, combined with the fact that most of these classes are very situational and not really all that useful (they bloat the framework and ruin semantic markup), ultimately led to the decision to **not** add the **atomic** css classes, as there is no actual use-case I can find for any of them and/or I have to alter parts of the framework that work well as-is. **However**, I'm going to provide more templates in the future, showcasing neat tricks (such as aligning a `<header>`'s menu differently) for beginners. I think that is to the benefit of everyone using the framework. More notes might also be added in the future to certain components.

At this point, pretty much everything is ready, so I will be releasing the next update before long.

**Closing issue, release imminent!**

**Comment by anselal** [comment]
Regarding the model class, in the documentation http://minicss.org/contextual#modals on the 'Do' Note the example is wrong, unless so intended. The <label> should be first and the <input> right before the <div class="modal">
Besides that, the modal in the Nord & Dark flavor is transparent. Is it supposed to be so ?

**Comment by Chalarangelo** [comment]
@anselal I see it, it seems like I made a mistake there. Thanks for pointing that out, I will be fixing it shortly.

As far as the transparency issue is concerned, I'm pretty sure the `.modal` itself has nothing to do with it. It seems to be a problem in the `.card` module's code. I'll open an issue and look into it soon.

**Comment by Chalarangelo** [comment]
@anselal The documentation has been updated and the issue seems to have been resolved. Thanks for reporting these problems! :)
